FROM maven:3.8.4-openjdk-17 as builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn package -DskipTests

FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY --from=builder /app/target/microservice-five-0.0.1-SNAPSHOT.jar /app/microservice-five.jar
CMD ["java", "-jar", "microservice-five.jar"]